dist: xenial
sudo: false

language: cpp

cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.icinga.com/ubuntu icinga-xenial main'
        key_url: 'https://packages.icinga.com/icinga.key'
    packages:
      - libboost1.67-icinga-all-dev
      - flex
      - bison
      - libssl-dev
      - libpq-dev
      - libmysqlclient-dev
      - libedit-dev
      - libyajl-dev
before_script:
  - arch=$(uname -m)
  - mkdir build
  - cd build
  - >
    cmake ..
    -DCMAKE_BUILD_TYPE=Debug
    -DICINGA2_UNITY_BUILD=Off
    -DCMAKE_INSTALL_PREFIX=/tmp/icinga2
    -DICINGA2_PLUGINDIR=/tmp/icinga2/sbin
    -DBoost_NO_BOOST_CMAKE=TRUE
    -DBoost_NO_SYSTEM_PATHS=TRUE
    -DBOOST_LIBRARYDIR=/usr/lib/${arch}-linux-gnu/icinga-boost
    -DBOOST_INCLUDEDIR=/usr/include/icinga-boost
    -DCMAKE_INSTALL_RPATH=/usr/lib/${arch}-linux-gnu/icinga-boost

script:
  - make
  - make test
  - make install
  - /tmp/icinga2/sbin/icinga2 --version
  - /tmp/icinga2/sbin/icinga2 daemon -C -DRunAsUser=$(id -u -n) -DRunAsGroup=$(id -g -n)
