---
version: 2.9.0.dev.{build}

os: Visual Studio 2017
platform: x64

environment:
  CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
  VSCMD_VER: 15.0
  # https://www.appveyor.com/docs/windows-images-software/#boost
  BOOST_ROOT: 'C:\Libraries\boost_1_66_0'
  BOOST_LIBRARYDIR: 'C:\Libraries\boost_1_66_0\lib64-msvc-14.1'
  BISON_BINARY: 'C:\ProgramData\chocolatey\lib\winflexbison3\tools\win_bison.exe'
  FLEX_BINARY: 'C:\ProgramData\chocolatey\lib\winflexbison3\tools\win_flex.exe'
  CMAKE_BUILD_TYPE: Debug

branches:
  only:
    - master

cache:
- build -> appveyor.yml
- C:\ProgramData\chocolatey\lib\winflexbison3

install:
- ps: |
    if (-not (Test-Path "C:\ProgramData\chocolatey\lib\winflexbison3")) {
      & choco install winflexbison3
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    }

# why that env handling, see
# https://help.appveyor.com/discussions/questions/18777-how-to-use-vcvars64bat-from-powershell#comment_44999171
before_build:
- ps: |
    $bits = $env:PLATFORM -replace "^x", ""
    cmd.exe /c "call `"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars${bits}.bat`" && set > `"${env:TEMP}\vcvars.txt`""
    Get-Content "$env:TEMP\vcvars.txt" | Foreach-Object {
      if ($_ -match "^(VSCMD.*?)=(.*)$") {
        Set-Content ("env:" + $matches[1]) $matches[2]
      }
    }

    if (-not (Test-Path ".\build\vendor\OpenSSL")) {
      & .\tools\win32\download-openssl.ps1
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
    }

    & .\tools\win32\configure.ps1
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

    del build\Icinga*.msi

build_script:
- ps: |
    & .\tools\win32\build.ps1
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

test_script:
- ps: |
    & .\tools\win32\test.ps1
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }

# Disable until we really need them
# https://github.com/Icinga/icinga2/issues/6106
# https://help.appveyor.com/discussions/problems/10253-maximum-allowed-artifact-storage-size-of-1000-mb-will-be-exceeded
#artifacts:
#- path: build/Icinga*.msi
#- path: build/choco/*.nupkg
#- path: build/Test.xml

deploy: off
