site_name: Icinga 2
docs_dir: doc
dev_addr: 0.0.0.0:8000
pages:
  - 'About Icinga 2': '01-about.md'
  - 'Getting Started': '02-getting-started.md'
  - 'Monitoring Basics': '03-monitoring-basics.md'
  - 'Configuring Icinga 2': '04-configuring-icinga-2.md'
  - 'Service Monitoring': '05-service-monitoring.md'
  - 'Distributed Monitoring': '06-distributed-monitoring.md'
  - 'Agent Based Monitoring': '07-agent-based-monitoring.md'
  - 'Advanced Topics': '08-advanced-topics.md'
  - 'Object Types': '09-object-types.md'
  - 'Icinga Template Library': '10-icinga-template-library.md'
  - 'CLI Commands': '11-cli-commands.md'
  - 'Icinga 2 API': '12-icinga2-api.md'
  - 'Addons': '13-addons.md'
  - 'Features': '14-features.md'
  - 'Troubleshooting': '15-troubleshooting.md'
  - 'Upgrading Icinga 2': '16-upgrading-icinga-2.md'
  - 'Language Reference': '17-language-reference.md'
  - 'Library Reference': '18-library-reference.md'
  - 'Technical Concepts': '19-technical-concepts.md'
  - 'Script Debugger': '20-script-debugger.md'
  - 'Development': '21-development.md'
  - 'SELinux': '22-selinux.md'
  - 'Migrating from Icinga 1.x': '23-migrating-from-icinga-1x.md'
  - 'Appendix': '24-appendix.md'
theme: readthedocs
markdown_extensions:
  - smarty
extra_javascript:
  - scroll.js
